### ISSUE TITLE
phabricator plugin start "git" process failed

### ISSUE THREAD

**Issue by tomatoi** [uber/phabricator-jenkins-plugin#132]
phabricator plugin version 1.9.1  
jenkins version 1.647
phabricator is upated to Feb 3 2016
i use git for Windows everyday
but i still get errors as follows:

[phabricator:conduit] Fetching differential from Conduit API
[workspace2] $ git reset --hard origin/master
java.io.IOException: Cannot run program "git" (in directory "D:\temp\workspace2"): CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessBuilder.start(Unknown Source)
	at hudson.Proc$LocalProc.<init>(Proc.java:244)
	at hudson.Proc$LocalProc.<init>(Proc.java:216)
	at hudson.Launcher$LocalLauncher.launch(Launcher.java:815)
	at hudson.Launcher$ProcStarter.start(Launcher.java:381)
	at hudson.Launcher$ProcStarter.join(Launcher.java:388)
	at com.uber.jenkins.phabricator.tasks.ApplyPatchTask.execute(ApplyPatchTask.java:90)
	at com.uber.jenkins.phabricator.tasks.Task.run(Task.java:58)
	at com.uber.jenkins.phabricator.PhabricatorBuildWrapper.setUp(PhabricatorBuildWrapper.java:125)
	at hudson.model.Build$BuildExecution.doRun(Build.java:156)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(Unknown Source)
	at java.lang.ProcessImpl.start(Unknown Source)
	... 15 more
[phabricator:arcanist] Error applying arc patch; got non-zero exit code FAILURE

**Comment by tomatoi** [comment]
i think i found the reason, after i reinstall git with "Use Git from the Windows Command Prompt" option, and restart jenkins,  this exception is gone.
