### ISSUE TITLE
com.uber.jenkins.phabricator.conduit.ConduitAPIException

### ISSUE THREAD

**Issue by Tectu** [uber/phabricator-jenkins-plugin#203]
Hi,

I followed your guide on how to get this plugin installed & working. I am able to successfully launch a Jenkins job out of Phabricator through Harbormaster. The build succeeds but reporting back to Phabricator is failing:
`
[phabricator:uberalls] No cobertura results found
[phabricator:non-differential-harbormaster] Sending diffusion result as: SUCCESS
com.uber.jenkins.phabricator.conduit.ConduitAPIException: org.apache.http.conn.EofSensorInputStream@59ff0295
	at com.uber.jenkins.phabricator.conduit.ConduitAPIClient.perform(ConduitAPIClient.java:79)
	at com.uber.jenkins.phabricator.conduit.HarbormasterClient.sendHarbormasterUri(HarbormasterClient.java:87)
	at com.uber.jenkins.phabricator.tasks.NonDifferentialHarbormasterTask.execute(NonDifferentialHarbormasterTask.java:81)
	at com.uber.jenkins.phabricator.tasks.Task.run(Task.java:58)
	at com.uber.jenkins.phabricator.PhabricatorNotifier.perform(PhabricatorNotifier.java:158)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1753)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:405)
Build step 'Post to Phabricator' marked build as failure
Finished: FAILURE
`

Unfortunately I'm unable to figure out what causes this issue and how to fix it.
The same problem has been mentioned twice (#174, #131 here already but the authors of the issues closed their issues without letting everybody else know what cause the issue and how they managed to fix it.

I'd be thankful for any kind of help.

**Comment by Tectu** [comment]
Okay, I managed to resolve this issue.

The way I tracked this down is by manually trying to use `arc call-conduit` on my Jenkins machine to talk back to Phabricator. After some fiddling around I found that `arc` always gets a a _**502 Bad Gateway**_ response back from the NGINX server where my Phabricator instance is hosted.
The NGINX error log showed the following: 
> upstream sent too big header while reading response header from upstream.
The issue was simply fixed by adding the following to the `/index.php` location in the NGINX config file:
```
fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;
```
And voila, everything works just fine :)

Thank you guys for providing this awesome plugin!
