### ISSUE TITLE
NullPointerException because of cobertura

### ISSUE THREAD

**Issue by benjamin-rtblw** [uber/phabricator-jenkins-plugin#204]
Hi,

I'm using the plugin version 1.9.7 and when I'm running a build on Jenkins, even without enabling Uberalls, I get the following exception :

```
12:32:43 ERROR: Build step failed with exception
12:32:43 java.lang.NullPointerException
12:32:43 	at hudson.plugins.cobertura.CoberturaXmlHandler.startElement(CoberturaCoverageParser.java:171)
12:32:43 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
12:32:43 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1358)
12:32:43 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2781)
12:32:43 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
12:32:43 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
12:32:43 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
12:32:43 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
12:32:43 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
12:32:43 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
12:32:43 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)
12:32:43 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
12:32:43 	at javax.xml.parsers.SAXParser.parse(SAXParser.java:195)
12:32:43 	at hudson.plugins.cobertura.CoberturaCoverageParser.parse(CoberturaCoverageParser.java:76)
12:32:43 	at hudson.plugins.cobertura.CoberturaCoverageParser.parse(CoberturaCoverageParser.java:52)
12:32:43 	at hudson.plugins.cobertura.CoberturaCoverageParser.parse(CoberturaCoverageParser.java:43)
12:32:43 	at com.uber.jenkins.phabricator.coverage.CoberturaCoverageProvider.computeCoverage(CoberturaCoverageProvider.java:123)
12:32:43 	at com.uber.jenkins.phabricator.coverage.CoberturaCoverageProvider.hasCoverage(CoberturaCoverageProvider.java:61)
12:32:43 	at com.uber.jenkins.phabricator.PhabricatorNotifier.getCoverageProvider(PhabricatorNotifier.java:252)
12:32:43 	at com.uber.jenkins.phabricator.PhabricatorNotifier.perform(PhabricatorNotifier.java:98)
12:32:43 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
12:32:43 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
12:32:43 	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
12:32:43 	at hudson.model.Build$BuildExecution.post2(Build.java:185)
12:32:43 	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
12:32:43 	at hudson.model.Run.execute(Run.java:1753)
12:32:43 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:32:43 	at hudson.model.ResourceController.execute(ResourceController.java:98)
12:32:43 	at hudson.model.Executor.run(Executor.java:404)
12:32:43 Build step 'Post to Phabricator' marked build as failure
12:32:43 Finished: FAILURE
```

Do you have a solution?

**Comment by artms** [comment]
Curious - do you still have same issue? Maybe you can provide cobertura coverage xml?
