### ISSUE TITLE
Cobertura plugin out of sync?

### ISSUE THREAD

**Issue by sujeet** [uber/phabricator-jenkins-plugin#233]
seems like the latest cobertura plugin deleted some methods which are still being used by this plugin...
```
ERROR: Step ?Post to Phabricator? aborted due to exception: 
java.lang.NoSuchMethodError: hudson.plugins.cobertura.targets.CoverageResult.setOwner(Lhudson/model/AbstractBuild;)V
	at com.uber.jenkins.phabricator.coverage.CoberturaCoverageProvider.computeCoverage(CoberturaCoverageProvider.java:131)
	at com.uber.jenkins.phabricator.coverage.CoberturaCoverageProvider.hasCoverage(CoberturaCoverageProvider.java:61)
	at com.uber.jenkins.phabricator.PhabricatorNotifier.getCoverageProvider(PhabricatorNotifier.java:252)
	at com.uber.jenkins.phabricator.PhabricatorNotifier.perform(PhabricatorNotifier.java:98)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
	at hudson.model.Run.execute(Run.java:1745)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:404)
```
https://github.com/jenkinsci/cobertura-plugin/issues/73

**Comment by artms** [comment]
Unfortunately phabricator-jenkins-plugin is not compatible with covertura > 1.9.8, api was changed in 1.10.X, you need to downgrade plugin to fix that issue.

**Comment by jeffpearce** [comment]
https://github.com/jenkinsci/cobertura-plugin/issues/73 fixes this exception, but I don't have an end-to-end configured to verify there aren't other issues lurking
