### ISSUE TITLE
On build failure, Harbormaster is not notified.

### ISSUE THREAD

**Issue by lavahot** [uber/phabricator-jenkins-plugin#26]
Having now restarted Harbormaster builds on my setup many times, I have noticed a trend that when the build fails (now every time, see #19), it does not send back a failure message to harbormaster. Instead Harbormaster patiently waits for the callback on that build and gives a status of "Building".

**Comment by sectioneight** [comment]
Can you post the build logs? Are you properly passing the PHID string parameter?

**Comment by lavahot** [comment]
Here's the harbormaster build logs:

>Build Log 14 (http://nvdbuild.cloudapp.net/buildByToken/buildWithParameters?job=Test&token=Sup3rl0NGTolk31n&DIFF_ID=1&PHID=PHID-HMBT-275ljsnmajwwtzl5k6br - http-body)
>1	Scheduled.
>2

**Comment by sectioneight** [comment]
Looks like I don't have permission to view the text. Could you paste me the output of the build log?

**Comment by sectioneight** [comment]
Also, does the job have String parameters for PHID and DIFF_ID (or perhaps they're being ignored?). Only way to tell is to see the build output

**Comment by lavahot** [comment]
Well, the build is broken for reasons I recently put into #19, but I'll paste a larger version here:

Usage Exception: This command requires arc to connect to a Phabricator install, but no
Phabricator installation is configured. To configure a Phabricator URI:

  - set a default location with `arc set-config default <uri>`; or
  - specify `--conduit-uri=uri` explicitly; or
  - run `arc` in a working copy with an '.arcconfig'.

[phabricator] Unable to parse JSON from response: 
FATAL: Invalid JSON String
net.sf.json.JSONException: Invalid JSON String
	at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:143)
	at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:103)
	at net.sf.json.groovy.JsonSlurper.parseText(JsonSlurper.java:80)
	at com.uber.jenkins.phabricator.conduit.ArcanistClient.callConduit(ArcanistClient.java:70)
	at com.uber.jenkins.phabricator.conduit.Differential.callConduit(Differential.java:85)
	at com.uber.jenkins.phabricator.conduit.Differential.<init>(Differential.java:49)
	at com.uber.jenkins.phabricator.PhabricatorBuildWrapper.setUp(PhabricatorBuildWrapper.java:87)
	at hudson.model.Build$BuildExecution.doRun(Build.java:156)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:537)
	at hudson.model.Run.execute(Run.java:1744)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Usage Exception: This command requires arc to connect to a Phabricator install, but no
Phabricator installation is configured. To configure a Phabricator URI:

  - set a default location with `arc set-config default <uri>`; or
  - specify `--conduit-uri=uri` explicitly; or
  - run `arc` in a working copy with an '.arcconfig'.

[phabricator] Unable to parse JSON from response: 
ERROR: Build step failed with exception
net.sf.json.JSONException: Invalid JSON String
	at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:143)
	at net.sf.json.JSONSerializer.toJSON(JSONSerializer.java:103)
	at net.sf.json.groovy.JsonSlurper.parseText(JsonSlurper.java:80)
	at com.uber.jenkins.phabricator.conduit.ArcanistClient.callConduit(ArcanistClient.java:70)
	at com.uber.jenkins.phabricator.conduit.Differential.callConduit(Differential.java:85)
	at com.uber.jenkins.phabricator.conduit.Differential.<init>(Differential.java:49)
	at com.uber.jenkins.phabricator.PhabricatorNotifier.perform(PhabricatorNotifier.java:117)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:726)
	at hudson.model.Build$BuildExecution.post2(Build.java:185)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:671)
	at hudson.model.Run.execute(Run.java:1769)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Build step 'Post to Phabricator' marked build as failure
Finished: FAILURE

**Comment by szhou1234** [comment]
I have the same failure for my patch https://code.uberinternal.com/D114594 <https://code.uberinternal.com/D114594>.

Thanks,
Simon from Supply Growth team

**Comment by sectioneight** [comment]
Simon, will you please file a ticket on internal phab and assign it to me
with devexp as the team?

**Comment by szhou1234** [comment]
Aiden,

Here it is: https://code.uberinternal.com/T101709 <https://code.uberinternal.com/T101709>

Thanks,
Simon from Supply Growth team

**Comment by lavahot** [comment]
So after properly configuring my instance to get source from the git repo with a correct uri, this works on both success and failure of the job. I think in the future there should be some URI settings for Jenkins so it doesn't have to rely on proper .arcconfig to update Phabricator, but instead prefer information from one if available.

Since my part in this is done, and Simon has his own ticket elsewhere, I'm going to close this. Thanks again!
