### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by jgelens** [uber/phabricator-jenkins-plugin#288]
After the upgrade to 2.0 I get the following error. The previous (old) version was working fine:
```
ERROR: Build step failed with exception
Also:   hudson.remoting.Channel$CallSiteStackTrace: Remote call to [redacted]
		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1741)
		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
		at hudson.remoting.Channel.call(Channel.java:955)
		at hudson.FilePath.act(FilePath.java:1036)
		at hudson.FilePath.act(FilePath.java:1025)
		at hudson.FilePath.list(FilePath.java:1840)
		at hudson.FilePath.list(FilePath.java:1824)
		at hudson.FilePath.list(FilePath.java:1809)
		at com.uber.jenkins.phabricator.PhabricatorNotifier.copyCoverageToJenkinsMaster(PhabricatorNotifier.java:353)
		at com.uber.jenkins.phabricator.PhabricatorNotifier.getCoverageProvider(PhabricatorNotifier.java:330)
		at com.uber.jenkins.phabricator.PhabricatorNotifier.perform(PhabricatorNotifier.java:232)
		at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
		at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
		at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
		at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
		at hudson.model.Build$BuildExecution.post2(Build.java:186)
		at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
		at hudson.model.Run.execute(Run.java:1823)
		at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
		at hudson.model.ResourceController.execute(ResourceController.java:97)
		at hudson.model.Executor.run(Executor.java:429)
java.lang.NullPointerException
	at hudson.FilePath.isAbsolute(FilePath.java:305)
	at hudson.FilePath.glob(FilePath.java:1862)
	at hudson.FilePath.access$2400(FilePath.java:209)
	at hudson.FilePath$23.invoke(FilePath.java:1843)
	at hudson.FilePath$23.invoke(FilePath.java:1840)
	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:2913)
	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
	at hudson.remoting.Request$2.run(Request.java:369)
	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Build step 'Post to Phabricator' marked build as failure
Finished: FAILURE
```

Any idea?

**Comment by jgelens** [comment]
Confirmed this works, thanks a lot !
