### ISSUE TITLE
NullPointerException in CoberturaXmlCoverageHandler

### ISSUE THREAD

**Issue by cmmata** [uber/phabricator-jenkins-plugin#294]
Hello,

We have a failed build with a NullPointerException error in Phabricator plugin. We have Jenkins ver. 2.150, Phabricator Differential Plugin 2.0.1, Clover Plugin 4.10.0, Clover PHP Plugin 0.5, and don't use Uberalls. The error trace is
```
ERROR: Build step failed with exception
java.lang.NullPointerException
	at com.uber.jenkins.phabricator.coverage.XmlCoverageProvider$CoberturaXmlCoverageHandler.parseCoverage(XmlCoverageProvider.java:186)
	at com.uber.jenkins.phabricator.coverage.XmlCoverageProvider.parse(XmlCoverageProvider.java:107)
	at com.uber.jenkins.phabricator.coverage.XmlCoverageProvider.computeCoverage(XmlCoverageProvider.java:83)
	at com.uber.jenkins.phabricator.coverage.CoverageProvider.computeCoverageIfNeeded(CoverageProvider.java:59)
	at com.uber.jenkins.phabricator.PhabricatorNotifier.getCoverageProvider(PhabricatorNotifier.java:332)
	at com.uber.jenkins.phabricator.PhabricatorNotifier.perform(PhabricatorNotifier.java:232)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1835)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Post to Phabricator' marked build as failure
```
It's a project with phpunit and it fails with and without code coverage. On October 29th we have the last successful build, that doesn't find Clover plugin to take the coverage part but it's ok for us. The output is
```
INFO: Stopping recording.
[phabricator:plugin-provider] 'cobertura' plugin not installed.
[phabricator:process-build-result] No line coverage found, skipping...
[phabricator:process-build-result] No coverage provider available.
[phabricator:file-fetcher] no files found by path: '.phabricator-lint'
[phabricator:harbormaster] Sending Harbormaster BUILD_URL via PHID: PHID-HMBT-ofgbdmaw5n2kde7lb3cv
[phabricator:send-harbormaster-uri] Harbormaster declined URI artifact: #1062: Duplicate entry 'uri-BtFETuiqLW_q' for key 'key_artifact'
[phabricator:process-build-result] Unable to send BUILD_URL to Harbormaster. This can be safely ignored, and is usually because it's already set.
[phabricator:process-build-result] Publishing unit results to Harbormaster for 68 tests.
[phabricator:process-build-result] Sending build result to Harbormaster with PHID PHID-HMBT-ofgbdmaw5n2kde7lb3cv, success: true
Finished: SUCCESS
```
The problem is upgrading Phabricator plugin to version 2.0.1. I'm not sure if previous version was 2.0 or 1.9.7, but going back to 1.9.7 causes the build to go well again.

**Comment by kageiit** [comment]
Fixed in 2.0.2
