### ISSUE TITLE
NullPointerExceptions with Jenkins Pipeline

### ISSUE THREAD

**Issue by na-Itms** [uber/phabricator-jenkins-plugin#296]
Since we upgraded the plugin to version 2.0.1, our pipeline jobs fail to publish to Phabricator and crash with:
```
java.lang.NullPointerException
	at com.uber.jenkins.phabricator.CommentBuilder.processBuildResult(CommentBuilder.java:149)
	at com.uber.jenkins.phabricator.BuildResultProcessor.processBuildResult(BuildResultProcessor.java:126)
	at com.uber.jenkins.phabricator.PhabricatorNotifier.perform(PhabricatorNotifier.java:259)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	...
```
The origin of the bug is that in `BuildResultProcessor`, the result is passed to the `CommentBuilder` without going through the sanitation step in `BuildResultProcessor.getBuildResult()` (where `null` results are interpreted as `SUCCESS`).

After fixing this, I also got 
```
java.lang.NullPointerException
	at com.uber.jenkins.phabricator.tasks.NonDifferentialHarbormasterTask.execute(NonDifferentialHarbormasterTask.java:84)
	at com.uber.jenkins.phabricator.tasks.Task.run(Task.java:49)
	at com.uber.jenkins.phabricator.PhabricatorNotifier.perform(PhabricatorNotifier.java:207)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	...
```
which is basically the same problem.

I am submitting a pull request.

Thank you for resuming upstream development, by the way! :tada:

**Comment by kageiit** [comment]
Fixed in https://github.com/na-Itms/phabricator-jenkins-plugin/commit/a7a55a67a4fe703a6174b829bbc6e296f794f7f4
