### ISSUE TITLE
NPE in PhabricatorNotifier, when used with pipeline (still)

### ISSUE THREAD

**Issue by AttwellBrian** [uber/phabricator-jenkins-plugin#317]
**Version**
I'm using version 2.1.1 of the plugin, which appears to contain a [fix intended for this issue issue](https://github.com/uber/phabricator-jenkins-plugin/commit/d0bdd17179b52ede56390b407bb1ea901a57bec5). 

**Steps to reproduce**
I write a very simple pipeline

```
pipeline {
  agent any

  stages {
    stage("Prepare") {
      steps {
        checkout scm
      }
    }

    stage("Gradle Check") {
      steps {
        sh "./gradlew check"
      }
    }
  }

  // Post built results back to phabricator.
  post {
    always {
      step([$class: 'PhabricatorNotifier', commentOnSuccess: false, commentWithConsoleLinkOnFailure: true])
    }
  }
}
```

This results in the following error

```
BUILD SUCCESSFUL in 1m 31s
30 actionable tasks: 30 executed
[Pipeline] }
[Pipeline] // stage
[Pipeline] stage
[Pipeline] { (Declarative: Post Actions)
[Pipeline] step
[phabricator:uberalls] Trying to obtain coverage metrics by parsing coverage xml files
[phabricator:uberalls] No coverage results found
Error when executing always post condition:
java.lang.NullPointerException
	at com.uber.jenkins.phabricator.CommentBuilder.processBuildResult(CommentBuilder.java:149)
	at com.uber.jenkins.phabricator.BuildResultProcessor.processBuildResult(BuildResultProcessor.java:126)
	at com.uber.jenkins.phabricator.PhabricatorNotifier.perform(PhabricatorNotifier.java:264)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:51)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:48)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline
java.lang.NullPointerException
	at com.uber.jenkins.phabricator.CommentBuilder.processBuildResult(CommentBuilder.java:149)
	at com.uber.jenkins.phabricator.BuildResultProcessor.processBuildResult(BuildResultProcessor.java:126)
	at com.uber.jenkins.phabricator.PhabricatorNotifier.perform(PhabricatorNotifier.java:264)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
	at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1$1.call(SynchronousNonBlockingStepExecution.java:51)
	at hudson.security.ACL.impersonate(ACL.java:290)
	at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution$1.run(SynchronousNonBlockingStepExecution.java:48)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Note that the original workaround for this issue, posted way back in issue #185, still works. If I add the following snippet to my `jenkinsfile` I won't see this crash.

```
post {
    always {
+      script {
+        currentBuild.result = currentBuild.currentResult
+      }
      step([$class: 'PhabricatorNotifier', commentOnSuccess: false, commentWithConsoleLinkOnFailure: true])
    }
  }
```

**Comment by AttwellBrian** [comment]
N/m. Missed up the release versions. The fix isn't in the latest release.
