### ISSUE TITLE
Fix compatibility with 2.241+

### ISSUE THREAD

**Issue by kthhrv** [uber/phabricator-jenkins-plugin#345]
It appears something changed in jenkins meaning this plugin doesn't work, PDP 2.1.3

```
ERROR: Build step failed with exception
java.lang.IllegalArgumentException: Method perform not found in com.uber.jenkins.phabricator.PhabricatorNotifier (or it is private, final or static)
	at hudson.Util.getMethod(Util.java:1462)
	at hudson.Util.isOverridden(Util.java:1439)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:110)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1905)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Build step 'Post to Phabricator' marked build as failure
Recording test results
```

the issue looks similar to https://issues.jenkins-ci.org/browse/JENKINS-62723

**Comment by srijan** [comment]
PR #344 is already open for this.

I tried the fix - it works for me.

**Comment by kthhrv** [comment]
Ah thanks, failed to spot that, closing this.
